model:
  name: float
  l1: 0.0001
  shape:
    - 64
    - 32
    - 32
  quantization:
    fc_bits: None
    fc_int_bits: None
    relu_bits: None
    input_bits: None
    input_int_bits: None
fit:
  batch_size: 1024
  compile:
    loss: categorical_crossentropy
    optimizer: adam
  epochs: 100
  shuffle: True
  validation_split: 0.25
  verbose: True
model_directory: ./model/float_baseline